spring:
  datasource:
    password: ${DB_USER}
    username: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/spring
  jpa:
    hibernate:
      ddl-auto: validate
  devtools:
    livereload:
      enabled: true

clients:
  open-library:
    base-url: https://openlibrary.org