spring:
  datasource:
    password: test
    username: test
    url: jdbc:postgresql://localhost:5432/book_review
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/spring
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    throw-exception-if-no-handler-found: true
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-1

server:
  error:
    include-exception: false
    include-stacktrace: on_param
    include-message: always
    include-binding-errors: always
clients:
  open-library:
    base-url: https://openlibrary.org

sqs:
  book-synchronization-queue: default
